### ISSUE TITLE
Issues cannot be scheduled (yet)

### ISSUE THREAD

**Issue by markiewb** [junichi11/netbeans-github-issues-plugin#6]
![image](https://cloud.githubusercontent.com/assets/1857095/5864835/48fc64d4-a285-11e4-91ac-3999357f6d54.png)

**Comment by junichi11** [comment]
Sorry, this feature has not been implemented yet.

**Comment by junichi11** [comment]
Done.

**Comment by junichi11** [comment]
@markiewb I've implement this feature like the followings:

- Set the due date to Preferences if we right-click on an issue node and click Schedule for > e.g. Monday.
- Get due dates from Preferences on when issue nodes are created.

But we can set a due date to a milestone. So I think that we should use it instead of my implementation. (i.e. It means that we can't set schedules from context menu.)  

What do you think?

**Comment by junichi11** [comment]
Changed.

Use a due date of a milestone.
